// <auto-generated />
using System;
using GameApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameApi.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameApi.Model.Leaderboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Leaderboard");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b497de8e-3af8-459c-8f1f-8bea386262b4"),
                            Name = "Ooowl",
                            Score = 2048
                        },
                        new
                        {
                            Id = new Guid("be63c866-e75f-45c1-baac-800eee5c4f7b"),
                            Name = "CoolGuy",
                            Score = 1024
                        },
                        new
                        {
                            Id = new Guid("de6192bc-0d38-4be6-9b39-c919dbb81b67"),
                            Name = "Toad",
                            Score = 4096
                        },
                        new
                        {
                            Id = new Guid("aba5f758-35db-4146-a055-5470f57731ac"),
                            Name = "PrincessPeach",
                            Score = 3016
                        },
                        new
                        {
                            Id = new Guid("ef298108-7856-43f9-84e3-aad6d061504d"),
                            Name = "Mario",
                            Score = 1048
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
